### ISSUE TITLE
Cannot pull docker image

### ISSUE THREAD

**Issue by b4cktr4ck5r3** [tiredofit/docker-lemonldap#14]
Hello,

I cannot pull docker image :

![image](https://user-images.githubusercontent.com/59377281/108390504-0c38ed80-7211-11eb-891f-ca02acd05c30.png)

Do you have any idea?

Thanks

**Comment by tiredofit** [comment]
I've pulled `latest` for the time being. Can you pull `tiredofit/2.0_alpine-1.9.3` for now?

**Comment by b4cktr4ck5r3** [comment]
yeah i founded this tag 5 minutes ago it worked perfectly, thanks a lot ! :p
