### ISSUE TITLE
CGI REMOTE_ADDR & Bad url

### ISSUE THREAD

**Issue by DanielB1990** [tiredofit/docker-lemonldap#16]
Hello!

First of all, thanks for packaging this great piece of software and adding more features to it!
I'm trying to use 'tiredofit/lemonldap:2.0_alpine-1.9.6' in my [Caprover](https://caprover.com) swarm, which uses nginx to reverse proxy.

So for so good, manager is reachable, I can login and all, but I seem to have 2 problems that I can't pin-point to being in the 'base' of lemonldap-ng or in the modifications/features you're adding.

The problem I have are:
- Bad URL ( _Reaching https://test.sso.example.nl for the first time_ )
- Login History shows "**10.0.0.5**", which correlates with "**REMOTE_ADDR**" on https://test.sso.example.nl below "**Environment for Perl CGI**".

The values for "**HTTP_X_FORWARDED_FOR**", "**HTTP_X_REAL_IP**" are set correctly, to my IP.

So I've been through both https://lemonldap-ng.org/documentation/2.0/behindproxyminihowto.html#http-header and https://lemonldap-ng.org/documentation/2.0/behindproxyminihowto.html#fixing-handler-redirections and those seem to be corrected here:

```
/etc/cont-init.d/10-nginx:  sed -i "s#<REAL_IP_HEADER>#${NGINX_REAL_IP_HEADER}#g" /etc/nginx/nginx.conf.d/reverse_proxy.conf
/etc/cont-init.d/10-nginx:  sed -i "s#<SET_REAL_IP_FROM>#${NGINX_SET_REAL_IP_FROM}#g" /etc/nginx/nginx.conf.d/reverse_proxy.conf
/etc/cont-init.d/10-nginx:  sed -i "\#include /etc/nginx/nginx.conf.d/reverse_proxy.conf;#d" /etc/nginx/nginx.conf

---

cat /etc/nginx/nginx.conf.d/reverse_proxy.conf
    real_ip_header X-Forwarded-For;
    set_real_ip_from 172.16.0.0/12;
```

And in `/etc/nginx/fastcgi_params` by the `/etc/cont-init.d/10-nginx` part, so my guess is, that it could be caused by:

```
nginx (caprover) > nginx ( tiredofit/lemonldap:2.0_alpine-1.9.6 container ) > llng-fastcgi-server
```

But am unsure how to handle this, would you have any guidance on this? Or would I need to reach out to lemonldap-ng themselves?

**Comment by DanielB1990** [comment]
Hi!

A) Yes, and A with wildcards to cover  the subdomains ( *multi-level* )
B) I've asked my colleague to check, which also gets the same results.

This is what happens via cURL & Browser.
I reckon it's the double redirect with "**?url=**" that is the problem.

I've decoded the base64 string behind "**?url=**" and added it below in between ( ... ) :

```
curl -IL https://test.sso.toolit.nl
HTTP/2 302
server: nginx
date: Fri, 19 Mar 2021 07:45:24 GMT
content-type: text/html
content-length: 145
location: http://auth.sso.toolit.nl/?url=aHR0cDovL3Rlc3Quc3NvLnRvb2xpdC5ubC8%3D ( http://test.sso.toolit.nl/7 )

HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Fri, 19 Mar 2021 07:45:24 GMT
Content-Type: text/html
Content-Length: 138
Connection: keep-alive
Location: https://auth.sso.toolit.nl/?url=aHR0cDovL3Rlc3Quc3NvLnRvb2xpdC5ubC8%3D?url=aHR0cDovL3Rlc3Quc3NvLnRvb2xpdC5ubC8%3D ( 1: http://test.sso.toolit.nl/7 ) ( 2: http://test.sso.toolit.nl/7 )

HTTP/2 400
server: nginx
date: Fri, 19 Mar 2021 07:45:24 GMT
content-type: text/html; charset=utf-8
content-length: 328
access-control-allow-origin: *
access-control-allow-credentials: true
access-control-allow-headers: *
access-control-allow-methods: POST,GET
access-control-expose-headers: *
access-control-max-age: 86400
```

**Comment by tiredofit** [comment]
Whats your Portal URL set to? Check to make sure it says https://.. not http:// (default) (General -> Portal -> URL)
Also lets try to make sure your Cookies are secure (General -> Cookies -> Secured Cookie (SSL) -> Secured Cookies (SSL)

Something is reminding me of similar issues in the past.

**Comment by DanielB1990** [comment]
I've checked the URL's and those were set to http:// and now changed to https:// as well as setting cookies to secure.
That fixed the Bad URL, thanks!

Any idea on the "**10.0.0.5**"?

**Comment by tiredofit** [comment]
Sadly no. I can't recreate that on my end. What I would like to do is put some time in the near future on the parent image (tiredofit/nginx) and enable functionality to move to "proxy" protocol as opposed to these header hacks. If you wanted to try that with changing the running config that would be helpful to let me know if it resovled it. Main Nginx configuration is here: /etc/nginx/nginx.conf and of course the LLNG stuff /etc/nginx/conf.d/ - `nginx -s reload` should do a live configuration reload without having to restart the container. 

Without having to hack away - there's also something you can try, is with the Vhost settings inside manager for your Portal URL and trying to change the settings for HTTPS from Default to On or Off. Take a backup of your config file ahead of time or just delete the new config that was saved in the filesystem to get things working again if it breaks.

**Comment by DanielB1990** [comment]
After getting in contact with the LemonLDAP community mailing list, my brain/thoughts were reset.

I needed to set the env variable `NGINX_SET_REAL_IP_FROM` to `127.0.0.1` from the official documentation, but in my case changing it to `10.0.0.5` resulted in showing the right REMOTE_ADDR, so for those looking here.

The the 'Last login' IP Address as `NGINX_SET_REAL_IP_FROM`.

Considered resolved.
