### ISSUE TITLE
example docker-compose.yml link doesn't work

### ISSUE THREAD

**Issue by LogX7** [tiredofit/docker-lemonldap#2]

**Comment by tiredofit** [comment]
Try this link for 1.9. The Readme needs to be updated in the root, there are also Readme's inside each of the folders.

I have an update coming out in the next day or two to all of the images with considerable changes. We have just gone live in our organization (7500 users) and some of the modifications make this truly production ready.

**Comment by LogX7** [comment]
thank you !
