### ISSUE TITLE
Nginx frontend + fastcgi -> Authentication required even if unprotect rule

### ISSUE THREAD

**Issue by benjamin-feron** [tiredofit/docker-lemonldap#28]
### Summary

Hello,
I encoured a problem with my setup.
I want to unprotect my web app home page.
In lemonldap, default rule is set on "unprotect" but when I visit my web app home page, I'm redirected to lemonldap authentication page.
After authentication success, web app works correctly.

### Steps to reproduce

Nginx reverse proxy configuration :

```yaml
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name app.mydomain.net;

    include /config/nginx/ssl.conf;

    location = /lmauth {
        internal;
        include /etc/nginx/fastcgi_params;
        fastcgi_pass lemonldap:2884; # "lemonldap" is correctly resolved.
        fastcgi_pass_request_body off;
        fastcgi_param CONTENT_LENGTH "";
        fastcgi_param HOST $http_host;
        fastcgi_param X_ORIGINAL_URI $original_uri;
    }

    location / {
        auth_request /lmauth;
        set $original_uri $uri$is_args$args;
        auth_request_set $lmremote_user $upstream_http_lm_remote_user;
        auth_request_set $lmlocation $upstream_http_location;
        error_page 401 $lmlocation;
        include /etc/nginx/lua/nginx-lua-headers.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        proxy_pass http://app.mylocaldomain.lan;
    }
}
```

Lemonldap _app.mydomain.net_ virtual host access rules :

| Comments   | Regular expression  | Rules      | Required auth levels |
| ---------------- | --------------------------- | ------------ | --------------------------- |
| Restricted    | ^/private                    | accept     |                                  |
| Default rule  | _default_                  | unprotect | _default_                  |

### What is the expected *correct* behavior?

Authentication form should not appear when access to `https://app.mydomain.net` but only on `https://app.mydomain.net/private`.

### Environment

- Image version / tag: tiredofit/lemonldap:2.0.16 
- Host OS: Debian 11.2

**Comment by tiredofit** [comment]
Hi, it may be best to pose this to the [lemonldap-ng users mailing list ](https://mail.ow2.org/wws/arc/lemonldap-ng-users)as I don't feel this is related to the container, but more application/configuration related.  I'm not sure however why this is occurring to you as it seems that you have everything correct and in place. The handler should theoretically trap that private request and leave your root as unprotected. 

Anything image related I'll be able to help here..

**Comment by coudot** [comment]
Yes, you can join the community on the mailing list. Maybe this issue is about the "required auth level" for the default rule, it should be empty.

**Comment by benjamin-feron** [comment]
Thank you for your responses.
@coudot, as you can see on the screenshot, "Required auth level" is empty for default rule :

![Capture d’écran du 2022-01-10 16-14-44](https://user-images.githubusercontent.com/50001976/148790473-e94689e6-e635-4052-9bcd-ef671b65163a.png)

I'll try to get help on the llng mailing list...

**Comment by benjamin-feron** [comment]
It works now... I don't know why but it works...
Thank you
