### ISSUE TITLE
PHPldapadmin

### ISSUE THREAD

**Issue by LogX7** [tiredofit/docker-lemonldap#3]
hi, i need to use it with phpldapadmin, is this possible ?

**Comment by tiredofit** [comment]
LemonLDAP:NG can use multiple authentication sources, one of them being an LDAP server. PHP LDAP Admin is more of an Administrative tool for your LDAP server, where as LemonLDAP:NG pulls from the server, so I don't see why not. Look into Fusion Directory though if you want a very nice LDAP/Directory management solution.
