### ISSUE TITLE
Text::Unidecode error

### ISSUE THREAD

**Issue by fawqsir** [tiredofit/docker-lemonldap#5]
I have been getting an error that Text::Unidecode is needed. I am using **tiredofit/lemonldap:2.0-alpine-latest**

Seems as though I have to install make, before I can install Text::Unidecode.

I used:
```
apk --no-cache add make
cpanm Text::Unidecode
```

**Comment by tiredofit** [comment]
Let me look into and issue a new image. A new version was released today of LLNG and it's a great release that solves some issues with LDAP.

Should have you something within a few hours.

**Comment by tiredofit** [comment]
I've brought my private repo in sync with this public one - It contains Text::Unidecode and also brings you up to LLNG 2.0.6 released this morning- Docker hub should have the image shortly!
