### ISSUE TITLE
Unable to go to portal

### ISSUE THREAD

**Issue by modem7** [tiredofit/docker-lemonldap#7]
Heya, 

I seem to be having some issues starting this app - I suspect it's an ID10T issue, unsure if you can assist?

I've got the following in my docker-compose:

>   lemonldap-app:
>     image: tiredofit/lemonldap:2.0-alpine-latest
>     container_name: LemonLDAP
>     volumes:
>     - Lemonldap-ng-etc:/etc/lemonldap-ng
>     - Lemonldap-ng-conf:/var/lib/lemonldap-ng/conf
>     - Lemonldap-ng-sessions:/var/lib/lemonldap-ng/sessions
>     - Lemonldap-ng-psessions:/var/lib/lemonldap-ng/psessions
>     - Lemonldap-ng-logs:/www/logs
>     #- ./assets/custom:/assets/custom
>     environment:
>     - VIRTUAL_HOST=sso.mydomain.com,manager.sso.mydomain.com,handler.sso.mydomain.com
>     - VIRTUAL_NETWORK=docker-macvlan
>     - VIRTUAL_PORT=80
>     - LETSENCRYPT_HOST=sso.mydomain.com,manager.sso.mydomain.com,handler.sso.mydomain.com,test.sso.mydomain.com
>     - LETSENCRYPT_EMAIL=myemail@mydomain.com
>     - ZABBIX_HOSTNAME=LemonLDAP
>     - MANAGER_HOSTNAME=manager.sso.mydomain.com
>     - PORTAL_HOSTNAME=sso.mydomain.com
>     - HANDLER_HOSTNAME=handler.sso.mydomain.com
>     - TEST_HOSTNAME=test.sso.mydomain.com
>     - TIMEZONE=Europe/London
>     networks:
>       docker-macvlan:
>         ipv4_address: '192.168.0.8'
>     cap_add:
>       - NET_ADMIN
>     privileged: true
>     restart: always

And the log files are:

>     today at 6:31 PM [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
>     today at 6:31 PM [s6-init] ensuring user provided files have correct perms...exited 0.
>     today at 6:31 PM [fix-attrs.d] applying ownership & permissions fixes...
>     today at 6:31 PM [fix-attrs.d] 00-functions: applying...
>     today at 6:31 PM [fix-attrs.d] 00-functions: exited 0.
>     today at 6:31 PM [fix-attrs.d] 01-s6: applying...
>     today at 6:31 PM [fix-attrs.d] 01-s6: exited 0.
>     today at 6:31 PM [fix-attrs.d] 02-zabbix: applying...
>     today at 6:31 PM [fix-attrs.d] 02-zabbix: exited 0.
>     today at 6:31 PM [fix-attrs.d] 03-logrotate: applying...
>     today at 6:31 PM [fix-attrs.d] 03-logrotate: exited 0.
>     today at 6:31 PM [fix-attrs.d] done.
>     today at 6:31 PM [cont-init.d] executing container initialization scripts...
>     today at 6:31 PM [cont-init.d] 00-startup: executing...
>     today at 6:31 PM [cont-init.d] 00-startup: exited 0.
>     today at 6:31 PM [cont-init.d] 01-timezone: executing...
>     today at 6:31 PM [NOTICE] ** [timezone] Setting timezone to 'Europe/London'
>     today at 6:31 PM [cont-init.d] 01-timezone: exited 0.
>     today at 6:31 PM [cont-init.d] 02-permissions: executing...
>     today at 6:31 PM [cont-init.d] 02-permissions: exited 0.
>     today at 6:31 PM [cont-init.d] 03-zabbix: executing...
>     today at 6:31 PM [cont-init.d] 03-zabbix: exited 0.
>     today at 6:31 PM [cont-init.d] 04-cron: executing...
>     today at 6:31 PM [cont-init.d] 04-cron: exited 0.
>     today at 6:31 PM [cont-init.d] 05-fail2ban: executing...
>     today at 6:31 PM [cont-init.d] 05-fail2ban: exited 0.
>     today at 6:31 PM [cont-init.d] 05-smtp: executing...
>     today at 6:31 PM [NOTICE] ** [smtp] Sendmail replaced and enabled to route mail to: 'postfix-relay'
>     today at 6:31 PM [cont-init.d] 05-smtp: exited 0.
>     today at 6:31 PM [cont-init.d] 06-rsyslog: executing...
>     today at 6:31 PM [WARN] ** [rsyslog] Disabling Syslog
>     today at 6:31 PM [cont-init.d] 06-rsyslog: exited 0.
>     today at 6:31 PM [cont-init.d] 10-lemonldap: executing...
>     today at 6:31 PM [cont-init.d] 10-lemonldap: exited 0.
>     today at 6:31 PM [cont-init.d] 10-nginx: executing...
>     today at 6:31 PM [NOTICE] ** [nginx] Disable Nginx FastCGI HTTPS Termination Support
>     today at 6:31 PM [cont-init.d] 10-nginx: exited 0.
>     today at 6:31 PM [cont-init.d] 11-nginx-config-reload: executing...
>     today at 6:31 PM [cont-init.d] 11-nginx-config-reload: exited 0.
>     today at 6:31 PM [cont-init.d] 20-llng-fastcgi-server: executing...
>     today at 6:31 PM ** [lemonldap-hander-socket] Enabling Handler TCP expose functionality. Socket listens at port  2884
>     today at 6:31 PM [cont-init.d] 20-llng-fastcgi-server: exited 0.
>     today at 6:31 PM [cont-init.d] 99-container: executing...
>     today at 6:31 PM [cont-init.d] 99-container: exited 0.
>     today at 6:31 PM [cont-init.d] done.
>     today at 6:31 PM [services.d] starting services
>     today at 6:31 PM [INFO] ** [nginx] Starting nginx 1.17.9
>     today at 6:31 PM [services.d] done.
>     today at 6:31 PM [INFO] ** [lemonldap-ng handler] Starting LemonLDAP FastCGI Server 2.0.7
>     today at 6:31 PM FastCGI: manager (pid 1845): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1913) started
>     today at 6:31 PM FastCGI: server (pid 1913): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1914) started
>     today at 6:31 PM FastCGI: server (pid 1914): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1915) started
>     today at 6:31 PM FastCGI: server (pid 1915): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1916) started
>     today at 6:31 PM FastCGI: server (pid 1916): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1917) started
>     today at 6:31 PM FastCGI: server (pid 1917): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1918) started
>     today at 6:31 PM FastCGI: server (pid 1918): initialized
>     today at 6:31 PM FastCGI: manager (pid 1845): server (pid 1919) started
>     today at 6:31 PM FastCGI: server (pid 1919): initialized
>     today at 6:31 PM Status: Unknown command line : RELOADCACHE  Cache::FileCache5
>     today at 6:31 PM [INFO] ** [zabbix] Starting Zabbix Agent
>     today at 6:31 PM [INFO] ** [fail2ban] Starting fail2ban
>     today at 6:32 PM [INFO] ** [cron] Starting cron

When I go to either the localip:2884 or handler.sso.mydomain.com, I get connection not secure, and even if I route it via nginx proxy manager to 2884, I get a "Bad Gateway" message served by Nginx

**Comment by tiredofit** [comment]
Looks like to be a pretty normal startup. The RELOADCACHE status I spoke to the developers and they said that it can be ignored.

Let's try to work this out:

- Can you head into the container and post the contents of `/etc/nginx/conf.d/handler.conf (change the urls)'

- Also, can you inside the container try a curl 127.0.0.1:2884 to see if any response? or even potentially a `curl 127.0.0.1:2884/status` 

Handler typically isn't really accessed publicly, but your proxy should still be issuing certificates for the hostname.

**Comment by modem7** [comment]
> server {
>   listen 80;
>   server_name handler.sso.mydomain.com;
>   root /var/www/html;
> 
>   access_log /www/logs/http/access-handler.log lm_combined;
>   error_log /www/logs/http/error-handler.log;
> 
>   location = /reload {
>     allow 127.0.0.1;
>     deny all;
>     include /etc/nginx/fastcgi_params;
>     fastcgi_pass 127.0.0.1:2884;
>     fastcgi_param LLTYPE reload;
>     fastcgi_param REMOTE_PORT 2884;
>   }
> 
>   # Client requests
>   location / {
>     deny all;
>   }
> 
>   location = /status {
>     allow 127.0.0.1;
>     deny all;
>     include /etc/nginx/fastcgi_params;
>     fastcgi_pass 127.0.0.1:2884;
>     fastcgi_param LLTYPE status;
>     fastcgi_param REMOTE_PORT 2884;
>   }
> }

> bash-5.0# curl 127.0.0.1:2884/status
> curl: (52) Empty reply from server

**Comment by tiredofit** [comment]
Great thanks. All looks well there. 
The fact that you are getting a Empty Reply from server as opposed to an error is showing the container can contact the handler. In reality, your reverse proxy should be able to access it as well, but the default configuration of LLNG points to "localhost" meaning:

- You visit Portal (which you cant do)
- You enter dwho/dwho to login 
- Portal talks internally to the handler (Port 2884) to get verification you are allowed to login
- Handler says OK and lets you in.

So, lets talk about what happens when you visit your portal site?

**Comment by modem7** [comment]
![image](https://user-images.githubusercontent.com/4349962/76358748-dfe2d480-6311-11ea-849a-fa1f401b546d.png)


Looks like letsencrypt hasn't done anything, nor is nginx routing things

Then if I add an exception, I get the following:

![image](https://user-images.githubusercontent.com/4349962/76358796-f852ef00-6311-11ea-8275-6e0ad21da367.png)

**Comment by tiredofit** [comment]
Hm, What about visiting portal.sso.domain.tld ?

**Comment by modem7** [comment]
Same thing - but I've had an idea as to why this is occurring. 

Current setup: 

Router > port forwarded 80 and 443 to a Nginx Proxy Manager container.
It's very probably that because of this particular setup, Nginx within the LemonLDAP isn't being honoured. 

Is there a particular setup that I should add to the NPM settings to forward traffic from those domains into the LLDAP container?

I tried the following but this didn't work as expected: 
![image](https://user-images.githubusercontent.com/4349962/76366342-a31ed980-6321-11ea-9e88-ae70821aa4d3.png)

The result is: 

![image](https://user-images.githubusercontent.com/4349962/76366372-b3cf4f80-6321-11ea-924c-c8cd113a3526.png)

**Comment by tiredofit** [comment]
OK, so I'm wondering if the Nginx Proxy Manager can't handle an image with 3 multiple domains on it. I'm not familiar with it to be honest, only have used `jwilder/nginx-proxy` in the past and now moved onto `tiredofit/traefik` for our uses. Looks like a cool tool though and I will investigate :)

Each of the services (portal, handler, test) should all route to port 80 in the container. Nginx internally handles the passing to the services properly. The handler.conf translates any connections sent to it to be sent to port 2884 of the handler service. So maybe make them all point to 80 and lets see if you get any success.

**Comment by tiredofit** [comment]
And just as some more maybe not useful information. The default design of LLNG is to use a .sock file for connection to the handler, but I found that I could get away with using a seperate container for LLNG which strictly used the handler functionality, and then point individual containers (like tiredofit/nginx or tiredofit/nginx-php-fpm) to use that handler avoiding having to run a handler in each container. That's the only time that 2884 would ever be exposed, and its internal only, never to the outside world in that fashion. That is where you would let Nginx sit in the middle and let its 80 protect the internals of the Handler.

What I described above may not make sense depending on the size of application you are looking to protect, or if you are getting heavy traffic. I have one server with 17 containers all pointing to the same handler and are handling hundreds of connections a second, and so far has been working fine.

**Comment by modem7** [comment]
OK, I think we're now getting somewhere! 

![image](https://user-images.githubusercontent.com/4349962/76369431-6e178480-632b-11ea-8e13-350a0d1d9dd2.png)

I've tried logging in via dwho/dwho but no joy - I think once we figure out this last hurdle, we should be golden!

Thank you for the help so far!

> 
> 
> OK, so I'm wondering if the Nginx Proxy Manager can't handle an image with 3 multiple domains on it. I'm not familiar with it to be honest, only have used `jwilder/nginx-proxy` in the past and now moved onto `tiredofit/traefik` for our uses. Looks like a cool tool though and I will investigate :)
> 
> Each of the services (portal, handler, test) should all route to port 80 in the container. Nginx internally handles the passing to the services properly. The handler.conf translates any connections sent to it to be sent to port 2884 of the handler service. So maybe make them all point to 80 and lets see if you get any success.

**Comment by tiredofit** [comment]
Re the IP - I believe you'll just need to figure out what header is being passed from NPM to the nginx services to make that correct. The LLNG image is a descendent of my [tiredofit/nginx](https://github.com/tiredofit/docker-nginx) image and there is a section in the README that should help with either changing the header or adjusting NPM to use its default.

Interesting that its saying it's connecting but not forwarding to the actual portal. Hows about once connected, are you able to visit the manager via hand typing it into the URL bar? Upon login it should forward to the actual application portal, so something is strange there. Might be worth deleting the data directory and starting fresh just in case to see if it fixes it as the first run mangles all sorts of configuration files.

I'll talk to my SysAdmin who just was trained on LLNG and see if he has sage advice to add as I seem to recall a few quirks on startup as well that were similar.

**Comment by modem7** [comment]
This is the current setup I have for the IP in NPM:

> 	add_header X-Frame-Options "SAMEORIGIN";
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header Host $http_host;
>         proxy_set_header X-NginX-Proxy true;
> 	proxy_set_header    X-Forwarded-Proto   $scheme;
> 	proxy_set_header    X-Forwarded-Ssl     on;

I've tried going to the manager, but it just redirects to sso.mydomain.com/?url=aHR0cDovL21hbmFnZXIuc3NvLm1vZGVtNy5jb20v

Same with test.sso.mydomain.com

**Comment by tiredofit** [comment]
Base64 unpacking that URL argument shows its trying to forward to a http:// url not https which could be the reason.

Everything looks cool from what I can see on your config (docker-compose) and the startup. I'm wondering if something changed in the upstream. Can you try pulling a different / earlier release of the image? The tags are [here](https://hub.docker.com/repository/registry-1.docker.io/tiredofit/lemonldap/tags?page=1]

I'm thinking if you go back one version (or more) we may be able to see if its an upstream issue that has occurred which means I'll have to figure out what has changed. 

Our production instance is only using LLNG 2.0.6 with cherrypicked patches from 2.0.7 and our own custom code so I just want to cancel out that it could be related to the 2.0.7 stock release.

**Comment by modem7** [comment]
Alrighty, tried 2.0_alpine-1.5.2 but still same issue (and IP as well).

I've also got the same base64 response of http.

Here's the config of NPM for the manager URL

![image](https://user-images.githubusercontent.com/4349962/76374458-2b5da880-633b-11ea-8da7-aedad8cfdf9b.png)

![image](https://user-images.githubusercontent.com/4349962/76374466-34e71080-633b-11ea-88de-12ecaba8784e.png)

![image](https://user-images.githubusercontent.com/4349962/76374479-3f090f00-633b-11ea-998a-987e049d00d6.png)

**Comment by tiredofit** [comment]
I'm stumped for now. I'll corner my sysadmin and see what he has to say. I'm sure its something right in our faces.

**Comment by modem7** [comment]
I appreciate that thank you!

As another test, I disabled HTTPS on NPM for each of the .sso.mydomain entries but still no change.
Hopefully it's the http part, question is, where is it generating that base64 value?

Also, if I try to manually put in a base64 value of https, it just goes back to the http value once I try to login, although the log files just happily say:

```
today at 2:13 AM [Wed Mar 11 02:13:15 2020] [LLNG:1120] [notice] Session granted for dwho by Demo (192.168.0.4)
today at 2:13 AM [Wed Mar 11 02:13:15 2020] [LLNG:1120] [notice] User dwho successfully authenticated at level 1
today at 2:13 AM [Wed Mar 11 02:13:15 2020] [LLNG:1120] [notice] dwho connected
```

**Comment by tiredofit** [comment]
Inside the container it would be in /var/lib/lemonldap-ng/conf/lmConf.js (or .json)
Probably easier however to delete all the volumes and start fresh as it should be able to write the correct protocols. I actually don't think I've ever not used this behind a SSL terminating proxy so I'm a bit baffled as to why its issuing http..

**Comment by modem7** [comment]
I've tried deleting and recreating, but unfortunately, still no go. 

Unsure if this will be useful:

```
  nginx:
    image: jc21/nginx-proxy-manager
    hostname: Nginx
    container_name: Nginx
    restart: always
    volumes:
      - 'NginxConfig:/app/config'
      - 'NginxData:/data'
      - 'Letsencrypt:/etc/letsencrypt'
    networks:
      docker-macvlan:
        ipv4_address: '192.168.0.4'
    labels: 
      - autoheal=true
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
      - FORCE_COLOR=1
    mem_limit: 500m
    mem_reservation: 200m
  
 #Nginx Database
  db:
    image: jc21/mariadb-aria
    restart: always
    container_name: Nginx_DB
    labels: 
      - autoheal=true
    networks:
      docker-macvlan:
        ipv4_address: '192.168.0.5'
    environment:
      TZ: "Europe/London"
      MYSQL_ROOT_PASSWORD=npm
      MYSQL_DATABASE=npm
      MYSQL_USER=npm
      MYSQL_PASSWORD=npm
    volumes:
      - NginxDB:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 250m
    mem_reservation: 100m
```

**Comment by nanobapt** [comment]
Hello,
I've got the same problem here. Does anyone has overcome the problem ?

**Comment by nanobapt** [comment]
Ok got it !
@modem7 look into your /data/var/lib/lemonldap-ng/conf/lmConf-1.json (somewhere define by the docker-compose) and make sur all domain are ok.
I had a problem due to wrong domain name at first, and this does the error of login. Now, it works.

**Comment by modem7** [comment]
Have decided on a different direction for authentication now. Using Traefik and Authelia for authentication. 

Thank you for all the help guys!
