### ISSUE TITLE
SAML authentification problem

### ISSUE THREAD

**Issue by nanobapt** [tiredofit/docker-lemonldap#8]
Hi,
I've been playing with you docker-compose file and it seems that the package crypt-openssl-509 is missing. Especially when you want to implement SAML for whatever reason. 

I solved my problem by installing the package inside the container (using docker exec xxx -it bash). Unfortunately, the package is not available in the APK version used in the container. I had the latest repository, then I installed the package.

>  echo http://dl-cdn.alpinelinux.org/alpine/edge/community>> /etc/apk/repositories
> apk update
>  apk add perl-crypt-openssl-x509

Thanx for your work,

Baptiste

**Comment by tiredofit** [comment]
I'll update the image for you shortly with the package embedded.

**Comment by tiredofit** [comment]
New release being built momentarily - Thanks for this. Something must have happened in the Alpine repositories for this to disappear/changed how the packages work, I've added it via Perl's CPAN manager.

**Comment by nanobapt** [comment]
Nop :) !
